# Read the Docs configuration file
#
# doc: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - pdf

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - rtd
