[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm[toml]>=3.4",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "fai/_version.py"
tag_regex = "^release/(?P<version>\\d+(\\.\\d+){2})$"
